### ISSUE TITLE
can't seem to get it to work

### ISSUE THREAD

**Issue by ar-stackrox** [magicspon/gatsby-spon-scss-postcss#1]
Hello, this seems like the exact plugin I need to use, but I keep coming across this issue. I even removed any notion of tailwind or postcss plugins from the config, and kept it to a single sass file. Am I missing some dependency or any ideas? Thanks @magicspon !

![image](https://user-images.githubusercontent.com/28272783/40566697-ce1c4a46-6026-11e8-8de2-569da35447ed.png)

**Comment by magicspon** [comment]
heyo...

this is plugin is a bit of hack to be honest.  You need to install postcss as well, the dependency alone doesn't seem to cut it (probably conflicting with gatsby).

anyhow... do you have an example i could look at.

cheers

ps. it looks like gatsby v2 will resolve the postcss issues

**Comment by ar-stackrox** [comment]
I cloned your repo actually, so I was able to get it to work. If there is any way that it can work on other scss files besides the main file, that would be so great. Thanks!

**Comment by ar-stackrox** [comment]
Ah yes, I saw that in v2 (though not sure when that will come out...). And I understand it's a hack, and I was missing some stuff on my end (But I cloned your example and that's working, and can copy that setup). Now my issue is that unfortunately the other sass files won't let you use @apply. It only works on the main .scss file.

Do you know when v2 could drop? My concern is that I need to start something soon and prefer this workflow.

**Comment by magicspon** [comment]
yup... that's the same issue i've got... @apply only works in the main file... not ideal...

also.. i've not worked out how to run this setup through purgecss

i've been using tailwind util classes mixed with styled components on my current project, so i've been able to avoid the '@apply' problem...

eeee!

**Comment by magicspon** [comment]
> Do you know when v2 could drop? My concern is that I need to start something soon and prefer this workflow.

not sure... i believe it's at beta at the moment... i could be wrong

**Comment by magicspon** [comment]
@ar-stackrox heyo....

i've had another stab at this... 

and it's awesome: tailwind in js!

https://github.com/magicspon/gatsby-starter-statamic

https://medium.com/andrewdelprete/using-tailwindcss-with-css-in-js-32ae6796f95c

**Comment by magicspon** [comment]
it's still a bit of a hack mind.... gatsby two should make the postcss stuff less shitty!
